### ISSUE TITLE
Too much parameters

### ISSUE THREAD

**Issue by tr3v3r** [EvgenyStralenya/React-course-work#1]
https://github.com/EvgenyStralenya/React-course-work/blob/2eaca97f33f0a13a50d267a7d1120ca5dd182466/src/api/getMovies.js#L1

Always try to create function with no more than 2 arguments! If you need more - use an object. It will help you don't worry about arguments order

```
export const getMovies = ({ inputValue, searchOption, sortOption, offsetMovie, limitMovie })

getMovies({ sortOption: 'asc', offsetMovie: 5, inputValue: 'matrix' })

```

**Comment by EvgenyStralenya** [comment]
Fixed
