### ISSUE TITLE
Cycle dependencies

### ISSUE THREAD

**Issue by tr3v3r** [EvgenyStralenya/React-course-work#2]
https://github.com/EvgenyStralenya/React-course-work/blob/2eaca97f33f0a13a50d267a7d1120ca5dd182466/src/components/AppContainer/AppContainer.js#L4

In this case you create cycle dependencies when you reference to the index.js from the AppContainer, but AppContainer also exported in index.js. When webpack will collect all files this could lead to unpredictable `undefined` values
**BAD**

```
import {
  MoviesContainer, Form, Footer, MovieControl, Modal,
} from '..';
```

**GOOD**

```
import { Form } from '../Form'
import { Footer } from '../Footer'
...
```

**Comment by EvgenyStralenya** [comment]
Fixed
