### ISSUE TITLE
Wrap switch with function

### ISSUE THREAD

**Issue by tr3v3r** [EvgenyStralenya/React-course-work#3]
https://github.com/EvgenyStralenya/React-course-work/blob/2eaca97f33f0a13a50d267a7d1120ca5dd182466/src/components/Button/Button.js#L8

more semantically correct create function with switch inside 

```

function getButtonStyle() {
  switch() {

 ....
 }

}


  function getClassNames() {
    return `${styles.button} ${getButtonStyle()} ${isActive ? styles.activeButton : ''}`;
  }

```

**Comment by EvgenyStralenya** [comment]
Fixed
