### ISSUE TITLE
Resetable  value

### ISSUE THREAD

**Issue by tr3v3r** [EvgenyStralenya/React-course-work#4]
https://github.com/EvgenyStralenya/React-course-work/blob/2eaca97f33f0a13a50d267a7d1120ca5dd182466/src/components/MoviesContainer/MoviesContainer.js#L12

In this case `isScroll` will be reset to `false` if  MoviesContainer re-render. So instead create such variables with [useRef](https://ru.reactjs.org/docs/hooks-reference.html#useref)

```
 const isScroll = useRef(false)


...

isScroll.currect = !isScrollCurrent

```

in this case re-render will not reset this value

**Comment by EvgenyStralenya** [comment]
Fixed
